# based on default config: https://github.com/alacritty/alacritty/blob/master/alacritty.yml
debug:
  persistent_logging: false

env:
  TERM: xterm-256color

shell:
  program: /bin/zsh
  args:
    - --login
    - -c
    - "tmux attach || tmux"

window:
  dynamic_title: true
  padding:
    x: 0
    y: 0
  decorations: none 
  startup_mode: Maximized

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: "Iosevka Nerd Font"
    style: Regular
  bold:
    style: Bold
  size: 22
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: true
  
# Atom One Light
colors:
  primary:
    background: "#fafafa"
    foreground: "#555555"
  cursor:
    text:       "#fcfdfe"
    cursor:     "#515253"
  normal:
    black:      "#0c0d0e"
    red:        "#e31a1c"
    green:      "#31aa44"
    yellow:     "#dca060"
    blue:       "#3182bd"
    magenta:    "#753bb1"
    cyan:       "#88aacc"
    white:      "#b7b8b9"
  bright:
    black:      "#111111"
    red:        "#d64a42"
    green:      "#64a550"
    yellow:     "#dca060"
    blue:       "#4e65f7"
    magenta:    "#756bb1"
    cyan:       "#80b1d3"
    white:      "#fcfdfe"

selection:
  save_to_clipboard: false

cursor:
  style: Block
  unfocused_hollow: true

key_bindings:
  # use "xxd" outside of tmux to find out codes for chars (e.g. ^B = \x02)
  - { key: Y, mods: Command, command: { program: "/bin/zsh", args: ["-l", "-c", "env | tee /tmp/alacritty_env"] } }
  - { key: R, mods: Command, command: { program: "/bin/zsh", args: ["-l", "-c", "tmux display-message 'Reload config'; tmux source-file ~/.tmux.conf"] } }

  # !!!MAC ONLY!!!
  # tmux proxy commands
  - { key: Q,          mods: Command,       action:  None }
  - { key: Q,          mods: Command|Shift, action:  Quit }
  - { key: A,          mods: Command,       chars:   "\x02\x77" }  # ^Bw
  - { key: W,          mods: Command,       chars:   "\x02x" } # kill-pane
  - { key: W,          mods: Command|Shift, chars:   "\x02&" } # kill-window
  - { key: T,          mods: Command,       chars:   "\x02c" } # new-window
  - { key: L,          mods: Command,       chars:   "\x02 " } # next-layout
  - { key: Comma,      mods: Command,       chars:   "\x02{" } # swap-pane
  - { key: Period,     mods: Command,       chars:   "\x02}" } # swap-pane
  - { key: LBracket,   mods: Command|Shift, chars:   "\x02p" } # next-window
  - { key: RBracket,   mods: Command|Shift, chars:   "\x02n" } # previous-window
  - { key: Semicolon,  mods: Command,       chars:   "\x02:" } # split-pane -
  - { key: Apostrophe, mods: Command,       chars:   "\x02\""} # split-pane |
  - { key: Up,         mods: Command,       chars:   "\x02\x1b\x5b\x41" }
  - { key: Down,       mods: Command,       chars:   "\x02\x1b\x5b\x42" }
  - { key: Right,      mods: Command,       chars:   "\x02\x1b\x5b\x43" }
  - { key: Left,       mods: Command,       chars:   "\x02\x1b\x5b\x44" }
  - { key: Key1,       mods: Command,       chars:   "\x02\x31" }  # ^B1
  - { key: Key2,       mods: Command,       chars:   "\x02\x32" }  # ^B2
  - { key: Key3,       mods: Command,       chars:   "\x02\x33" }  # ^B3
  - { key: Key4,       mods: Command,       chars:   "\x02\x34" }  # ^B4
  - { key: Key5,       mods: Command,       chars:   "\x02\x35" }  # ^B5
  - { key: Key6,       mods: Command,       chars:   "\x02\x36" }  # ^B6
  - { key: Key7,       mods: Command,       chars:   "\x02\x37" }  # ^B7
  - { key: Key8,       mods: Command,       chars:   "\x02\x38" }  # ^B8
  - { key: Key9,       mods: Command,       chars:   "\x02\x39" }  # ^B9
